# Copyright (C) 2024  C-PAC Developers

# This file is part of C-PAC.

# C-PAC is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.

# C-PAC is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
# License for more details.

# You should have received a copy of the GNU Lesser General Public
# License along with C-PAC. If not, see <https://www.gnu.org/licenses/>.
fail_fast: false

repos:
- repo: https://github.com/python-poetry/poetry
  rev: 1.8.0
  hooks:
  - id: poetry-lock
  - id: poetry-check

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.7
  hooks:
  - id: ruff
    args: [--fix]
  - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.9.0
  hooks:
  - id: mypy
    additional_dependencies:
    - https://github.com/FCP-INDI/C-PAC/archive/pyproject.toml.zip
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.13.0
  hooks:
  - id: pretty-format-yaml
    args:
    - --autofix
    - --indent=2
  - id: pretty-format-toml
    exclude: ^poetry.lock$
    args:
    - --autofix
    - --indent=2
    - --no-sort

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-case-conflict
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: pretty-format-json
    args:
    - --autofix
    - --indent=4
    - --no-sort-keys
  - id: check-merge-conflict
  - id: check-yaml
  - id: check-json
  - id: check-toml

- repo: local
  hooks:
  - id: yaml-file-extension
    name: Prefer .yaml over .yml.
    entry: YAML files must have .yaml extension.
    language: fail
    files: \.yml$
